### ISSUE TITLE
Suddenly no longer appears?

### ISSUE THREAD

**Issue by tylerFowler** [jakemarsh/atom-spotify#14]
I noticed this a few updates ago, it seems that the text just no longer appears in the status bar. If I turn the waveform on I can see a blank bar at the bottom appear, but no song/artist data (not even the musical note icon). 

I ran the package specs and it seems that there were some deprecations for the way that `View` is used, I know Atom has been deprecating a lot of things in that area lately. Also I just updated Spotify right before I noticed the package was broken, so the problem could be there too. I might take a look at the issue later this weekend.

Spotify Version: `0.9.15.27.g87efe634`

**Comment by lack3r** [comment]
Does not work for me either.
