### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by AgentAntelope** [jakemarsh/atom-spotify#16]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
AtomSpotifyStatusBarView.initialize (/Users/felltir/.atom/packages/atom-spotify/lib/atom-spotify-status-bar-view.coffee:18:9)
```

**Comment by keeev** [comment]
:+1:

**Comment by a9io** [comment]
+1
