### ISSUE TITLE
Unsupported platform on latest 1.2.0 update?

### ISSUE THREAD

**Issue by sebabal** [jakemarsh/atom-spotify#18]
Hi I am getting the following msg today when trying to update the package.

```
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: atom-spotify@1.2.0
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: ia32
```

Any ideas? BTW, I am on Windows 8.1

**Comment by paulbeattie** [comment]
@sebabal atom-spotify doesn't support Windows, it only works on OS X as it relies on AppleScript through the spotify-node-applescript package (https://github.com/andrehaveman/spotify-node-applescript).

You were able to install this on Windows before as there was no OS requirement, this was introduced in ddeea61 and then released with 1.2.0.

**Comment by jakemarsh** [comment]
Yep, I was about to respond with exactly what @paulbeattie said @sebabal.

@paulbeattie thanks! :+1:

**Comment by sebabal** [comment]
Ah, thanks for the reply.
