### ISSUE TITLE
Spotify 1.0.1.x - Not working

### ISSUE THREAD

**Issue by albertorestifo** [jakemarsh/atom-spotify#19]
I'm beta-testing Spotify (`1.0.1.988.g8f17a348` currently).

They have changes a lot in the API in the beta, and the plugin doesn't seem to work.

I restarted both Atom and Spotify after the installation.

**Comment by blimmer** [comment]
I just tried installing this extension and it's not working for me either. I'm on production spotify version `1.01.1060.gc75ebdfd`.

**Comment by tylerFowler** [comment]
Have been using this for a while but seemed to suddenly stop working directly (and I mean one minute it works one minute it's not) after I updated to Spotify version `1.1.1.1060.gc75ebdfd`. And this update had some non minor changes it seems.

**Comment by dawidk92** [comment]
+1

**Comment by nicolasbrugneaux** [comment]
Works fine when using my (very) small fix here https://github.com/andrehaveman/spotify-node-applescript/pull/20

Apparently `starred` api has been removed

**Comment by tylerFowler** [comment]
+1 On this fix, it works fine after that.

**Comment by kjschulz** [comment]
+1 Simple & quick fix, it works great now!

**Comment by albertorestifo** [comment]
:+1:  The solution proposed by @nicolasbrugneaux worked. I'm closing the issue since it's not with this package.

We should all +1 the @nicolasbrugneaux  PR
